### ISSUE TITLE
Dashboard page failing to update Virt-Node info

### ISSUE THREAD

**Issue by diogogmt** [diogogmt/webvirt#34]
The dashboard page is not refreshing and pulling data from new Virt-Node ips.

To recreated the bug:

Remove all IPs
Do a full post back
Go to the Virt-Node management tab
Add some IPs
Go go the dashboard by clicking on the menu button
Nothing is displayed

Expected result:
The info about the new IPs should be displayed right away.

**Comment by sedge** [comment]
Solved, though there's a new bug (issue 53)
