### ISSUE TITLE
UI should display raw error messages 

### ISSUE THREAD

**Issue by diogogmt** [diogogmt/webvirt#35]
Since this is a debug tool, the UI should display the raw error messages with toastr to help the user figure it out the problem.

**Comment by sedge** [comment]
Could we get them displayed on the log page?

**Comment by diogogmt** [comment]
The log page is displaying all the errors/info/exceptions logged in the server.

What I mean about raw error messages is that the UI shouldn't parse them before displaying to the user.
So if something goes wrong with an action, instead of just saying "Action error.", the raw message returned by virt should be displayed.
