### ISSUE TITLE
Dashboard crashes if IP is unavailable

### ISSUE THREAD

**Issue by diogogmt** [diogogmt/webvirt#39]
If a virt-node IP is saved and suddenly the connection is dropped, the dashboard crashes and doesn't load any other hosts.

**Comment by sedge** [comment]
Is this a result of the polling?  Is it the Backbone app that is crashing?

**Comment by diogogmt** [comment]
We are not implementing any polling in the app currently.

The bug here is that the UI is trying to get some info about an IP, however the IP is down, so the server returns an error that the UI is not expecting.

The UI should fail gracefully if an error is returned from the server.
We can display a toastr msg informing the error and what the user can do to solve it.

**Comment by sedge** [comment]
Can you provide steps to replicate this bug?

**Comment by sedge** [comment]
Got it.
